## O NumPy ndarray: um objeto de matriz multidimensional

Um dos principais recursos do NumPy é seu objeto de matriz N-dimensional, ou ndarray,
que é um contêiner rápido e flexível para grandes conjuntos de dados em Python. Matrizes permitem que você
executar operações matemáticas em blocos inteiros de dados usando sintaxe semelhante à
operações equivalentes entre elementos escalares.

Para dar uma idéia de como o NumPy permite cálculos em lote com sintaxe semelhante
para escalar valores em objetos Python internos, primeiro importo o NumPy e gero uma pequena
matriz de dados aleatórios:

In [6]:
import numpy as np

In [7]:
data = np.random.randn(2,3) # Gerando dados aleatoriamente 

In [8]:
data

array([[ 0.12025942, -1.66022531, -1.22092929],
       [ 0.4472005 ,  0.70759607, -1.01013556]])

#### Em seguida escrevo operações matemáticas com dados

In [10]:
data * 10

array([[  1.20259419, -16.60225312, -12.20929288],
       [  4.47200498,   7.07596075, -10.10135565]])

In [11]:
data + data

array([[ 0.24051884, -3.32045062, -2.44185858],
       [ 0.894401  ,  1.41519215, -2.02027113]])

No primeiro exemplo, todos os elementos foram multiplicados por 10. No segundo, o
valores correspondentes em cada “célula” na matriz foram adicionados um ao outro.

Um ndarray é um contêiner multidimensional genérico para dados homogêneos; isso é tudo
dos elementos deve ser do mesmo tipo. Cada matriz tem uma forma, uma tupla indicando o
tamanho de cada dimensão e um dtype, um objeto que descreve o tipo de dados da matriz:

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')


Este capítulo apresentará os conceitos básicos do uso de matrizes NumPy e deve ser
suficiente para acompanhar o restante do livro. Embora não seja necessário
ter um profundo entendimento do NumPy para muitas aplicações analíticas de dados, tornando-se
proficiente em programação e pensamento orientados a array é um passo fundamental
caminho para se tornar um guru científico do Python.

## Criando ndrrays
A maneira mais fácil de criar uma matriz é usar a função da matriz. Isso aceita qualquer
objeto do tipo sequência (incluindo outras matrizes) e produz uma nova matriz NumPy contendo
os dados passados. Por exemplo, uma lista é um bom candidato para conversão:

In [14]:
data1 = [6,7.5,8,0,1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Seqüências aninhadas, como uma lista de listas de igual comprimento, serão convertidas em uma multidimensional
matriz:

In [17]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [18]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Como data2 era uma lista de listas, o array NumPy arr2 tem duas dimensões com forma
inferido a partir dos dados. Podemos confirmar isso inspecionando o ndim e a forma
atributos:

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

A menos que seja explicitamente especificado (mais sobre isso posteriormente), o np.array tenta inferir um bom dado
digite para a matriz que ele cria. O tipo de dados é armazenado em um metadado especial de tipo
objeto; por exemplo, nos dois exemplos anteriores, temos:

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

Além do np.array, existem várias outras funções para criar novos
matrizes. Como exemplos, zeros e uns criam matrizes de 0s ou 1s, respectivamente, com um
dado comprimento ou forma. vazio cria uma matriz sem inicializar seus valores para qualquer particular
valor. Para criar uma matriz dimensional mais alta com esses métodos, passe uma tupla
para a forma:

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

arange é uma versão com valor de matriz da função de intervalo Python integrada:

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Tipos de dados para ndarrays
O tipo ou tipo de dados é um objeto especial que contém as informações (ou metadados,
dados sobre dados) o ndarray precisa interpretar um pedaço de memória como um
tipo de dados:

In [28]:
arr1 = np.array([1,2,3],dtype = np.float64)

In [29]:
arr2 = np.array([1,2,3],dtype = np.int32)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('int32')

dtypes são uma fonte da flexibilidade do NumPy para interagir com dados provenientes de outros
sistemas. Na maioria dos casos, eles fornecem um mapeamento diretamente para um disco subjacente ou
representação de memória, o que facilita a leitura e gravação de fluxos binários de dados
ao disco e também para conectar-se ao código escrito em uma linguagem de baixo nível como C ou Fortran.
Os tipos numéricos são nomeados da mesma maneira: um nome de tipo, como float ou int, seguido
por um número indicando o número de bits por elemento. Uma dupla decisão padrão
valor de ponto flutuante (o que é usado sob o capô no objeto flutuante do Python)
ocupa 8 bytes ou 64 bits. Portanto, esse tipo é conhecido no NumPy como float64. Vejo
Tabela 4-2 para obter uma lista completa dos tipos de dados suportados pelo NumPy.


Você pode converter ou converter explicitamente uma matriz de um dtype para outro usando o ndarray's
método astype:

In [33]:
arr = np.array([1,2,3,4,5])

In [34]:
arr.dtype

dtype('int32')

In [37]:
arr_float = arr.astype(np.float64)

In [38]:
arr_float.dtype

dtype('float64')

Neste exemplo, números inteiros foram convertidos em ponto flutuante. Se eu lançar algum ponto flutuante
Se o número for do tipo inteiro, a parte decimal será truncada:

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [40]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [41]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [42]:
arr.dtype

dtype('float64')

Se você tiver uma matriz de cadeias representando números, poderá usar astype para converter
para a forma numérica:

In [43]:
numeric_string = np.array(['1.25','-9.6','42'],dtype = np.string_)

In [44]:
numeric_string.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

Se a conversão falhar por algum motivo (como uma sequência que não pode ser convertida em
float64), um ValueError será gerado.
Aqui eu estava um pouco preguiçoso e escrevi float

In [45]:
int_array = np.arange(10)

In [46]:
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype = np.float64)

In [47]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Existem cadeias de código de tipo abreviado que você também pode usar para se referir a um dtype:

In [48]:
empty_uin32 =np.empty(8,dtype = 'u4') 

In [49]:
empty_uin32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)