## Aritmética com matrizes NumPy

Matrizes são importantes porque permitem expressar operações em lote com dados
sem escrever nenhum para loops. Os usuários do NumPy chamam isso de vetorização. Qualquer aritmética
As operações entre matrizes de tamanho igual aplicam a operação em elementos:

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

Operações aritméticas com escalares propagam o argumento escalar para cada elemento em
a matriz:

In [7]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparações entre matrizes do mesmo tamanho produzem matrizes booleanas:

In [9]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [10]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [11]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

As operações entre matrizes de tamanhos diferentes são chamadas de transmissão e serão discutidas
mais detalhadamente no Apêndice A. Ter uma compreensão profunda da transmissão é
não é necessário para a maior parte deste livro.

## Indexação básica e fatiamento

A indexação de array NumPy é um tópico interessante, pois há várias maneiras de selecionar
um subconjunto de seus dados ou elementos individuais. Matrizes unidimensionais são simples; em
Na superfície, eles agem de maneira semelhante às listas Python:

In [12]:
arr = np.arange(10)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [15]:
 arr[5:8]

array([5, 6, 7])

In [16]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Como você pode ver, se você atribuir um valor escalar a uma fatia, como em arr [5: 8] = 12, o valor é
propagada (ou transmitida a partir de agora) para toda a seleção. Uma primeira distinção importante
das listas internas do Python é que as fatias da matriz são visualizações na matriz original.
Isso significa que os dados não são copiados e quaisquer modificações na exibição serão
refletido na matriz de origem.

Para dar um exemplo disso, primeiro criei uma fatia de arr:

In [17]:
arr_slice = arr[5:8] 

In [18]:
arr_slice

array([12, 12, 12])