## Transpondo matrizes e trocando eixos
A transposição é uma forma especial de remodelagem que, de maneira semelhante, retorna uma visão sobre o subjacente
dados sem copiar nada. As matrizes têm o método de transposição e também o
atributo T especial:

In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3,5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Ao fazer cálculos matriciais, você pode fazer isso com muita frequência - por exemplo, quando
computando o produto da matriz interna usando np.dot:

In [7]:
arr = np.random.randn(6,3)
arr

array([[ 0.90367805,  1.50660752,  0.19756361],
       [-0.66793426, -1.23712018, -0.17940349],
       [-1.74487768,  0.34326469,  1.33256924],
       [ 0.77296094,  1.03992931, -1.63167466],
       [-0.18536168,  1.35991635, -0.60934874],
       [ 0.90730896,  0.11100718, -0.16085217]])

In [8]:
np.dot(arr.T,arr)

array([[ 5.76240544,  2.24131438, -3.32102018],
       [ 2.24131438,  6.86131125, -1.56632691],
       [-3.32102018, -1.56632691,  4.90649926]])

Para matrizes dimensionais mais altas, a transposição aceita uma tupla de números de eixos para permitir
os eixos (para flexão extra da mente):

In [11]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Para matrizes dimensionais mais altas, a transposição aceita uma tupla de números de eixos para permitir
os eixos (para flexão extra da mente):

In [13]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [16]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])


similarmente, as swapaxes retornam uma visualização dos dados sem fazer uma cópia.

## 4.2 Funções universais: matriz inteligente de elemento rápido
Funções

Uma função universal, ou ufunc, é uma função que executa operações por elementos
em dados em ndarrays. Você pode pensar neles como invólucros vetorizados rápidos para
funções que recebem um ou mais valores escalares e produzem um ou mais resultados escalares.
Muitos ufuncs são simples transformações em elementos, como sqrt ou exp:

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [22]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Estes são referidos como ufuncos unários. Outros, como adicionar ou máximo, recebem duas matrizes
(portanto, ufuncs binários) e retorne uma única matriz como resultado:

In [26]:
x = np.random.randn(8)
y = np.random.randn(8)

In [27]:
x

array([ 1.02313272, -0.08020538, -1.00313774,  0.43112452, -1.20307154,
       -0.47424031,  0.14832041,  0.56383362])

In [28]:
y

array([ 0.12125362,  0.65928685, -0.97790275,  0.14108307, -1.27101652,
       -0.01984477, -1.10766844,  0.22192365])

In [30]:
np.maximum(x,y)

array([ 1.02313272,  0.65928685, -0.97790275,  0.43112452, -1.20307154,
       -0.01984477,  0.14832041,  0.56383362])

Aqui, numpy.maximum calculou o máximo em elementos dos elementos em x e
y

Embora não seja comum, um ufunc pode retornar várias matrizes. modf é um exemplo, um vetorizado
versão do divmod interno do Python; retorna o fracionário e integral
partes de uma matriz de ponto flutuante:

In [31]:
arr = np.random.randn(7) * 5

In [32]:
arr

array([-0.465275  ,  2.48907965,  4.25429475,  0.08642549,  3.14743974,
       -3.17979991,  5.10374932])